add_newline = false

# Use custom format
format = "\\[ $username$directory$git_branch$git_status$python\\]\\$ " 

[git_branch]
symbol = ""
[git_status]
deleted = ""

[python]
format = "[$virtualenv]($style)"
disabled = false


[username]
show_always = true
format = '[$user ]($style)'